### ISSUE TITLE
Autoload every permutation at load time

### ISSUE THREAD

**Issue by loic-enedis** [daimresearch/sb-addon-permutation-table#13]
**Is your feature request related to a problem? Please describe.**
Our team is running storybook on chromatic to run visual testing. 
We want to limit our visual testing to some stories with many stories in one. So we made a template to show many variants in the same story. 
We would like to change our solution to go on permutation table. 

**Describe the solution you'd like**
We would like permutation-table to enable every permutation at load time (or using any feature we can run before visual testing of chromatic, like play feature of storybook), with an option to enable it on a story.

**Describe alternatives you've considered**
If not possible, maybe we could automatically generate a story using permutation-table for a component ?

**Additional context**
Nothing more, that is a great project, well done !!

**Comment by dongyunlee-daim** [comment]
Our team has discussed this issue and concluded that the feature you suggest is a necessary one for this add-on. We believe it will be implemented by planting an additional flag on the parameter.

We haven't decided on the specific API yet, but we will implement flags to enable all permutations, flags to enable only certain permutations, and, of course, a deactivate function.

If there are any further changes, we'll update this issue

**Comment by dongyunlee-daim** [comment]
![Jun-07-2023 15-41-50](https://github.com/daimresearch/sb-addon-permutation-table/assets/107913240/6da289b0-22a0-404b-a460-253b3eb20bde)

Our team was successful in piloting the feature and is currently testing the code. While the development of the feature has just been completed, we want to ensure careful testing to ensure its importance and proper operation. As soon as we're done testing, we'll deploy a stable version.

Thank you for your continued support and patience. We look forward to seeing you with new features soon.

**Comment by dongyunlee-daim** [comment]
We're closing this issue because the feature has been fully implemented in version 0.1.2

**Comment by loic-enedis** [comment]
So great ! Thank you for that feature 👍
