### ISSUE TITLE
[BUG] Styling gets injected into the page

### ISSUE THREAD

**Issue by tim-richter** [daimresearch/sb-addon-permutation-table#28]
**Describe the bug**

Styling for the permutation table is being applied to table elements in stories. This causes table styling from components to break.

**To Reproduce**
1. Have a story with a 'table' element in it
2. Inspect and see that only browser styling is applied
3. Install and include sb-addon-permutation-table in storybook
4. See that the table now has additional styles applied to it (like 'text-align: center' for example)

Or use this repro in stackblitz: https://stackblitz.com/edit/github-ypvo3z?file=src%2Fstories%2FTable.jsx

**Expected behavior**
The styling in stories should not be affected by sb-addon-permutation-table

**Screenshots**

Before installing the plugin: 
![image](https://github.com/daimresearch/sb-addon-permutation-table/assets/43145310/7fb39d54-41a5-4f3e-8727-7964d66ccc7f)

After: 
![image](https://github.com/daimresearch/sb-addon-permutation-table/assets/43145310/675385ac-cbe8-4929-8446-05c9ed1aa484)

Styling applied to a td (just as an example there are more stylings): 
![image](https://github.com/daimresearch/sb-addon-permutation-table/assets/43145310/4b75dc72-5194-45ef-8291-8fb2d7957589)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Chrome
 - Version: Version 114.0.5735.198 (Official Build) (64-bit)

**Comment by dongyunlee-daim** [comment]
There's a piece of code that I think might be causing this.
we'll work on it together as we move forward with the next style-related patch. I have another ticket right now, so it's a little difficult to fix it right away. Thank you for your understanding

**Comment by tim-richter** [comment]
No problem. Thanks for the feedback! If you need help with that fix let me know :slightly_smiling_face:

**Comment by dongyunlee-daim** [comment]
@tim-richter We fixed this 😉 We're way behind schedule, can you try v.1.0.2?
