### ISSUE TITLE
Addon causes radio input controls to lose their selection

### ISSUE THREAD

**Issue by shrink** [daimresearch/sb-addon-permutation-table#30]
1. Visit a Storybook with the addon enabled, e.g: https://daimresearch.github.io/sb-addon-permutation-table
2. Pick a Story with controls, e.g: [Example > NestedComponent > Primary](https://daimresearch.github.io/sb-addon-permutation-table/?path=/story/example-nestedcomponent--primary)
3. Select a radio option, e.g: "small"
4. Switch back and forth between options

The option will change (as is evidenced by the URL changing) but the radio option itself will "flash" and lose selection. The issue appears to impact all stories once the addon is installed. The issue does not appear to impact the function of the Storybook controls -- the options still apply -- so this is not a breaking issue, more so it's just a bit confusing.

[![](https://cdn.loom.com/sessions/thumbnails/ed1e8b06cd344ed49d67118f7ccc344c-with-play.gif)](https://www.loom.com/share/ed1e8b06cd344ed49d67118f7ccc344c?sid=93a342d5-e19f-42f3-9703-5c32fa841f6c)

Thanks!

**Comment by dongyunlee-daim** [comment]
I will check this with #28 Thanks for reporting this!

**Comment by dongyunlee-daim** [comment]
@shrink omg I fixed this in #26. but I didn't apply the updated version of addon in our deploy site.... I totally forgot it. We'll update it right away, sorry!

**Comment by dongyunlee-daim** [comment]
![Aug-01-2023 13-34-52](https://github.com/daimresearch/sb-addon-permutation-table/assets/107913240/ba7e1871-2a94-4348-99d2-00140627f7bd)

@shrink We fixed this 😉 In v.1.0.2, you won't find this inconvenience
