### ISSUE TITLE
Permutation for storybook 8

### ISSUE THREAD

**Issue by vasilkovalyov** [daimresearch/sb-addon-permutation-table#36]
Hi, Is it possible install permutation to storybook 8? I have issues because of dependencies older verisons

**Comment by dongyunlee-daim** [comment]
No it won't install if you use storybook8 because of the peer dependency settings of the addon. are you trying to use it with storybook8? I will try to update the addon if necessary.

**Comment by vasilkovalyov** [comment]
yes please, it is crucial for me)

вт, 27 авг. 2024 г. в 04:14, 이동윤 ***@***.***>:

**Comment by dongyunlee-daim** [comment]
I'll do my best. Thank you for loving this project.
However, with SB8, the Addon API has changed a lot, and I need to revise the entire code base. Also, since this project is separate from my day job, development time may be a bit slower.

**Comment by vasilkovalyov** [comment]
no problem, I will wait) your addon awesome and essential for my work
project and I really thank you for your effort

вт, 27 авг. 2024 г. в 10:13, 이동윤 ***@***.***>:

**Comment by dongyunlee-daim** [comment]
We just released v.1.0.3, which has been tested in an SB8 environment. Could you please try updating the package?? If you encounter any issues, please open an additional issue.

**Comment by vasilkovalyov** [comment]
Hi, thanks, check it out

пт, 30 авг. 2024 г. в 10:25, 이동윤 ***@***.***>:

**Comment by vasilkovalyov** [comment]
[image: image.png]
[image: image.png]
after install the addon, I ran the app and get issues in console

пт, 30 авг. 2024 г. в 10:28, Vasiliy Kovalyov ***@***.***>:

**Comment by SpookyJelly** [comment]
I can't see the image you attached. Could you check again?

**Comment by dongyunlee-daim** [comment]
I can't see the image you attached. Could you please check again?

**Comment by dongyunlee-daim** [comment]
Close with prolonged inactivity
